apiVersion: report.k8s.aws/v1alpha1
kind: InterAZTraffic
metadata:
  labels:
    app.kubernetes.io/name: aws-inter-az-traffic-analyzer
    app.kubernetes.io/managed-by: kustomize
  name: interaztraffic-sample
  namespace : inter-az-traffic-analyzer-system
spec:
  vpcId: vpc-0c2101f28902f28e7
  startFrom: "2025-11-12T18:30:00Z"
  endTo: "2025-11-12T18:40:00Z"
